name: Sync

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:paritybit-ai/XFL.git
          destination-repo: git@gitee.com:basebit-ai/XFL.git
